Repository Chemaclass/JiraStatusNotifier, pull requests merged in 2019-11, with the labels that each got.

#9 Display slack name next to jira ticket
  src/ScrumMaster/Command/SlackNotifierOutput.php
  src/ScrumMaster/Slack/ReadModel/SlackTicket.php
  src/ScrumMaster/Slack/SlackNotifier.php
  src/ScrumMaster/Slack/SlackNotifierResult.php
  tests/Unit/ScrumMaster/Command/SlackNotifierCommandTest.php
  tests/Unit/ScrumMaster/Command/SlackNotifierOutputTest.php
Labels: enhancement

#13 Test EchoOutput class
  tests/Unit/ScrumMaster/Command/IO/EchoOutputTest.php
Labels: enhancement

#12 Show successful and failed ticket-keys next to the notification total
  src/ScrumMaster/Command/SlackNotifierOutput.php
  tests/Unit/ScrumMaster/Command/SlackNotifierOutputTest.php
Labels: enhancement

#16 Ignore send notifications to certain users
  .env.dist
  README.md
  src/ScrumMaster/Command/SlackNotifierCommand.php
  src/ScrumMaster/Command/SlackNotifierInput.php
  src/ScrumMaster/Slack/SlackNotifier.php
  tests/ScrumMaster/Unit/Command/SlackNotifierCommandTest.php
  tests/ScrumMaster/Unit/Concerns/JiraApiResource.php
Labels: enhancement

#18 Apply some minor optimizations and cleaning
  src/ScrumMaster/Command/Exception/UndefinedParameter.php
  src/ScrumMaster/Command/SlackNotifierInput.php
  src/ScrumMaster/Command/SlackNotifierOutput.php
  src/ScrumMaster/Jira/Board.php
  src/ScrumMaster/Jira/BoardInterface.php
  src/ScrumMaster/Jira/JqlUrlBuilder.php
  src/ScrumMaster/Slack/ReadModel/SlackTicket.php
  src/ScrumMaster/Slack/SlackNotifier.php
  src/ScrumMaster/Slack/SlackNotifierResult.php
  tests/ScrumMasterTest/Unit/Command/SlackNotifierOutputTest.php
Labels: improvement

#19 Move SlackMessage up to be injected to the SlackNotifierCommand
  examples/using-dot-env.php
  src/ScrumMaster/Command/SlackNotifierCommand.php
  src/ScrumMaster/Slack/MessageTemplate/MessageGeneratorInterface.php
  src/ScrumMaster/Slack/MessageTemplate/SlackMessage.php
  src/ScrumMaster/Slack/SlackNotifier.php
  tests/ScrumMasterTest/Unit/Command/SlackNotifierCommandTest.php
  tests/ScrumMasterTest/Unit/Slack/SlackMessageTest.php
Labels: improvement

#20 Abstract the "channel" from the "notifier"
  README.md
  docu/mandatory-parameters.md
  docu/slack-notifications.md
  examples/using-dot-env.php
  src/ScrumMaster/Channel/ChannelInterface.php
  src/ScrumMaster/Channel/ChannelResultInterface.php
  src/ScrumMaster/Channel/ReadModel/ChannelIssue.php
  src/ScrumMaster/Command/NotifierCommand.php
  src/ScrumMaster/Command/NotifierInput.php
  src/ScrumMaster/Command/NotifierOutput.php
  src/ScrumMaster/Command/SlackNotifierCommand.php
  src/ScrumMaster/Command/SlackNotifierOutput.php
  src/ScrumMaster/Slack/SlackChannel.php
  src/ScrumMaster/Slack/SlackNotifier.php
  src/ScrumMaster/Slack/SlackNotifierResult.php
  tests/ScrumMasterTest/Unit/Command/NotifierCommandTest.php
  tests/ScrumMasterTest/Unit/Command/NotifierInputTest.php
  tests/ScrumMasterTest/Unit/Command/NotifierOutputTest.php
  tests/ScrumMasterTest/Unit/Command/SlackNotifierOutputTest.php
Labels: improvement

#21 Split the `Output` from the Command
  examples/using-dot-env/app.php
  src/ScrumMaster/Channel/ChannelInterface.php
  src/ScrumMaster/Command/NotifierCommand.php
  src/ScrumMaster/Command/NotifierOutput.php
  src/ScrumMaster/Slack/SlackChannel.php
  tests/ScrumMasterTest/Unit/Command/NotifierCommandTest.php
Labels: improvement

#23 Add github pull-request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#22 Run the commands from local or docker context
  bin/bash
  bin/composer
  bin/csfix
  bin/tests
Labels: enhancement, improvement

#25 Improve ByPassEmail
  src/ScrumMaster/Channel/Email/ByPassEmail.php
  src/ScrumMaster/Channel/Email/Channel.php
  src/ScrumMaster/Channel/Email/MailerClient.php
  src/ScrumMaster/Channel/Email/MessageGenerator.php
  src/ScrumMaster/Channel/ReadModel/ChannelIssue.php
  src/ScrumMaster/Channel/Slack/Channel.php
  tests/ScrumMasterTest/Functional/EmailNotifierCommandTest.php
  tests/ScrumMasterTest/Unit/Channel/Email/ByPassEmailTest.php
  tests/ScrumMasterTest/Unit/Concerns/JiraApiResource.php
Labels: improvement

#27 Use SymfonyMailer
  composer.json
  composer.lock
  docu/email-notifications.md
  examples/using-email-channel/.env.dist
  examples/using-email-channel/app.php
  src/ScrumMaster/Channel/Email/Channel.php
  src/ScrumMaster/Channel/Email/MailerClient.php
  src/ScrumMaster/Channel/Email/ReadModel/EmailAddress.php
  src/ScrumMaster/Channel/Email/ReadModel/Message.php
  src/ScrumMaster/Channel/Email/ReadModel/ToAddress.php
  tests/ScrumMasterTest/Functional/EmailNotifierCommandTest.php
  tests/ScrumMasterTest/Unit/Channel/Email/MailerClientTest.php
Labels: improvement
