Repository Chemaclass/JiraStatusNotifier, pull requests merged in 2020-01, with the labels that each got.

#37 Bugfix in Tickets::fromJiraResponse()
  src/ScrumMaster/Jira/Tickets.php
Labels: bug, improvement

#36 Install twig
  composer.json
  composer.lock
  examples/templates/output/channel-result.twig
  examples/using-all-channels/app.php
  examples/using-email-channel/app.php
  examples/using-slack-channel/app.php
  src/ScrumMaster/IO/NotificationOutputExtractor.php
  src/ScrumMaster/IO/NotifierOutput.php
  tests/ScrumMasterTest/Unit/Channel/ChannelResultTest.php
  tests/ScrumMasterTest/Unit/IO/NotificationOutputExtractorTest.php
  tests/ScrumMasterTest/Unit/IO/NotifierOutputTest.php
Labels: enhancement, help wanted, improvement, question

#39 PHP 7.4 as minimum PHP version
  .travis.yml
  composer.json
  composer.lock
  devops/dev/php.dockerfile
Labels: enhancement
