Repository Chemaclass/JiraStatusNotifier, pull requests merged in 2020-03, with the labels that each got.

#45 Send a unique slack message per user
  src/ScrumMaster/Channel/ChannelResult.php
  src/ScrumMaster/Channel/Slack/Channel.php
  src/ScrumMaster/Channel/Slack/MessageGenerator.php
  tests/ScrumMasterTest/Unit/Channel/Slack/MessageGeneratorTest.php
Labels: enhancement, improvement

#46 Create email-template.twig
  examples/templates/email-template.twig
  examples/using-all-channels/console
  examples/using-email-channel/console
  src/ScrumMaster/Channel/Email/MessageGenerator.php
  tests/ScrumMasterTest/Functional/EmailNotifierCommandTest.php
  tests/ScrumMasterTest/Unit/Channel/Slack/MessageGeneratorTest.php
Labels: improvement

#47 Replace empty array key by none when nobody is assigned to a JiraTicket
  src/ScrumMaster/Channel/ChannelResult.php
  tests/ScrumMasterTest/Unit/Channel/ChannelResultTest.php
Labels: enhancement

#49 Use Twig for slack messages
  examples/templates/slack-template.twig
  examples/using-slack-channel/console
  src/ScrumMaster/Channel/Slack/MessageGenerator.php
  src/ScrumMaster/Jira/Tickets.php
  tests/ScrumMasterTest/Functional/SlackNotifierTest.php
  tests/ScrumMasterTest/Unit/Channel/Slack/JiraMappingTest.php
  tests/ScrumMasterTest/Unit/Channel/Slack/MessageGeneratorTest.php
Labels: enhancement, improvement

#50 Move MessageGenerator up to Channel level
  examples/using-all-channels/console
  examples/using-email-channel/console
  examples/using-slack-channel/console
  src/ScrumMaster/Channel/Email/Channel.php
  src/ScrumMaster/Channel/MessageGenerator.php
  src/ScrumMaster/Channel/MessageGeneratorInterface.php
  src/ScrumMaster/Channel/Slack/Channel.php
  src/ScrumMaster/Channel/Slack/MessageGenerator.php
  tests/ScrumMasterTest/Functional/CliNotifierTest.php
  tests/ScrumMasterTest/Functional/EmailNotifierTest.php
  tests/ScrumMasterTest/Functional/SlackNotifierTest.php
  tests/ScrumMasterTest/Unit/Channel/MessageGeneratorTest.php
  tests/ScrumMasterTest/Unit/Jira/TicketsTest.php
Labels: improvement

#52 Make EchoOutputTest class final and strict
  tests/ScrumMasterTest/Unit/IO/EchoOutputTest.php
Labels: enhancement, improvement

#55 Replace bin folder by a Makefile
  Makefile
  bin/bash
  bin/composer
  bin/csfix
  bin/tests
Labels: enhancement, improvement
